[package]
name = "cielo-driver"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cielo"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
cielo = { package = "cielo-compiler", path = "../cielo-compiler" }
cielo-base = { path = "../cielo-base" }
cielo-frontend = { path = "../cielo-frontend" }
cielo-ir = { path = "../cielo-ir" }
cielo-staging = { path = "../cielo-staging" }
