[package]
name = "cielo"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
bitflags = "2.11.0"
clap = { version = "4.5.32", features = ["derive"] }
indexmap = "2.13.0"
lasso = "0.7.3"
miette = { version = "7.6.0", features = ["fancy"] }
rustc-hash = "2.1.1"
smallvec = "1.15.1"
thiserror = "2.0.18"

[[bench]]
name = "v1_pipeline"
harness = false

[[bench]]
name = "v1_runtime"
harness = false
