[workspace]
resolver = "2"
members = [
    "crates/cielo-base",
    "crates/cielo-ir",
    "crates/cielo-frontend",
    "crates/cielo-sema",
    "crates/cielo-staging",
    "crates/cielo-lowering",
    "crates/cielo-runtime",
    "crates/cielo-db",
    "crates/cielo-memory",
    "crates/cielo-backend-api",
    "crates/cielo-backend-c",
    "crates/cielo-compiler",
    "crates/cielo-driver",
]
