[package]
name = "cielo-db"
version = "0.1.0"
edition = "2024"

[dependencies]
cielo-base = { path = "../cielo-base" }
cielo-backend-c = { path = "../cielo-backend-c" }
cielo-frontend = { path = "../cielo-frontend" }
cielo-ir = { path = "../cielo-ir" }
cielo-memory = { path = "../cielo-memory" }
cielo-lowering = { path = "../cielo-lowering" }
cielo-runtime = { path = "../cielo-runtime" }
cielo-sema = { path = "../cielo-sema" }
cielo-staging = { path = "../cielo-staging" }
salsa = { version = "0.28.0", features = ["salsa_unstable"] }
